# These are supported funding model platforms

github: [semi-column]
# ko_fi: # Replace with your Ko-fi username
# buy_me_a_coffee: # Replace with your Buy Me a Coffee username
# custom: ['https://your-custom-link.com']
